services:
  plataforma-a:
    image: si-sma-jade:latest
    build: .
    container_name: plataforma-a
    command: [
        "java",
        "-cp",
        "app.jar",
        "jade.Boot",
        "-gui",
        "-name",
        "plataforma-a",
        # "-mtp",
        # "jade.mtp.http.MessageTransportProtocol(http://plataforma-a:7778/acc)",
      ]
    ports:
      - "1099:1099"
      - "7778:7778"
    networks:
      - si-sma-jade-network

  contenedor-1a-gestion:
    image: si-sma-jade:latest
    container_name: contenedor-1a-gestion
    depends_on:
      - plataforma-a
    command:
      [
        "java",
        "-cp",
        "app.jar",
        "jade.Boot",
        "-container",
        "-host",
        "plataforma-a",
        "-container-name",
        "contenedor-1a-gestion",
        "-agents",
        "restaurante:edu.unmsm.fisi.AgenteRestaurante;coordinador:edu.unmsm.fisi.CoordinatorAgent",
      ]
    networks:
      - si-sma-jade-network

    # plataforma-b:
    #   image: si-sma-jade:latest
    #   container_name: plataforma-b
    #   command: [
    #       "java",
    #       "-cp",
    #       "app.jar",
    #       "jade.Boot",
    #       "-gui",
    #       "-name",
    #       "plataforma-b",
    #       "-mtp",
    #       "jade.mtp.http.MessageTransportProtocol(http://plataforma-b:7778/acc)",
    #     ]
    #   ports:
    #     - "1100:1099"
    #     - "7779:7778"
    #   networks:
    #     - si-sma-jade-network

  contenedor-1b-clientes:
    image: si-sma-jade:latest
    container_name: contenedor-1b-clientes
    depends_on:
      - plataforma-a
    command:
      [
        "java",
        "-cp",
        "app.jar",
        "jade.Boot",
        "-container",
        "-host",
        "plataforma-a",
        "-container-name",
        "contenedor-1b-clientes",
        "-agents",
        "cliente1:edu.unmsm.fisi.AgenteCliente;cliente2:edu.unmsm.fisi.AgenteCliente",
      ]
    networks:
      - si-sma-jade-network

  contenedor-2b-deliveries:
    image: si-sma-jade:latest
    container_name: contenedor-2b-deliveries
    depends_on:
      - plataforma-a
    command:
      [
        "java",
        "-cp",
        "app.jar",
        "jade.Boot",
        "-container",
        "-host",
        "plataforma-a",
        "-container-name",
        "contenedor-2b-deliveries",
        "-agents",
        "delivery1:edu.unmsm.fisi.AgenteDelivery;delivery2:edu.unmsm.fisi.AgenteDelivery;delivery3:edu.unmsm.fisi.AgenteDelivery",
      ]
    networks:
      - si-sma-jade-network
networks:
  si-sma-jade-network:
