services:
  plataforma-a:
    image: si-sma-jade:latest
    build: .
    container_name: plataforma-a
    command:
      [
        "java",
        "-cp",
        "app.jar",
        "jade.Boot",
        "-gui",
        "-name",
        "PlataformaA",
        "-agents",
        "persona1:edu.unmsm.fisi.AgenteAlarmado(fuego);bridge:edu.unmsm.fisi.AgentePuente(bomb@PlataformaB)",
        "-mtp",
        "jade.mtp.http.MessageTransportProtocol(http://plataforma-a:7778/acc)",
      ]
    ports:
      - "1099:1099"
      - "7778:7778"
    networks:
      - si-sma-jade-network

  plataforma-b:
    image: si-sma-jade:latest
    container_name: plataforma-b
    depends_on:
      - plataforma-a
    command:
      [
        "java",
        "-cp",
        "app.jar",
        "jade.Boot",
        "-gui",
        "-name",
        "PlataformaB",
        "-agents",
        "bomb:edu.unmsm.fisi.AgenteBombero",
        "-mtp",
        "jade.mtp.http.MessageTransportProtocol(http://plataforma-b:7778/acc)",
      ]
    ports:
      - "1100:1099"
      - "7779:7778"
    networks:
      - si-sma-jade-network

networks:
  si-sma-jade-network:
